name: Store API CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t store-api .